version: '3.9'
services:
    db:
        image: postgres:15.3
        container_name: shopping-db
        restart: always
        environment:
          POSTGRES_PASSWORD: mysecretpassword
        ports: 
            - "5432:5432"
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
    backend:
      image: shopping/api
      container_name: shopping-api
      build:
        context: ./backend
        dockerfile: Dockerfile.dev
      volumes:
        - ./backend/src:/api-app/src
      command: sh ./docker-entrypoint.sh
      ports:
        - 8080:8080
        - 35729:35729
        - 5005:5005
      depends_on:
        - db
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://db:5432/postgres
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: mysecretpassword
      restart: always
volumes: 
    postgres_data: